import type { Metadata } from "next";

import "./globals.css";
import { FaCalendarAlt } from "react-icons/fa";
import { FormProvider } from "@/libs/context/FormContext";

export const metadata: Metadata = {
  title: "Multipage-Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-green-900 flex items-start pt-10 w-screen justify-center h-[300px]">
          <div className="w-screen mx-10 ">
            <hr className="border-t-1 border-neutral-400" />
            <h1 className="text-white text-4xl font-semibold mt-10">Visits</h1>
            <div className="mt-20 bg-white rounded-t-md h-[100px]">
              <div className="flex gap-10 justify-start items-center h-full pl-10">
                <FaCalendarAlt size={30} />
                <h1 className="text-3xl font-bold">Register a new visit</h1>
              </div>
              <hr className=" w-[80%] border-t-1 border-gray-300 mx-auto" />
            </div>
          </div>
        </header>
        <FormProvider>{children}</FormProvider>
      </body>
    </html>
  );
}
